=== xcomart/libcmdbm/data/cmdbm_config.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Configuration (Databases Logging PoolConfigurations)>
<!ELEMENT Databases ((ODBC|Oracle|MySQL|SQLite|PgSql|Custom)+)>

<!ELEMENT ODBC (DSN? Database? User? Password? Param* Pool Mappers)>
<!ATTLIST ODBC
    id ID #REQUIRED
    charset CDATA #REQUIRED
    dsn CDATA #IMPLIED
    database CDATA #IMPLIED
    user CDATA #IMPLIED
    password CDATA #IMPLIED>
<!ELEMENT DSN (#PCDATA)>
<!ELEMENT User (#PCDATA)>
<!ELEMENT Password (#PCDATA)>
<!ELEMENT Database (#PCDATA)>
<!ELEMENT Pool (PingInterval? PingTest? TestOnBorrow? InitCount? MaxCount? TestSql?)>
<!ATTLIST Pool
    confRef IDREF #REQUIRED
    pingInterval CDATA #IMPLIED
    pingTest (true|false) #IMPLIED
    testOnBorrow (true|false) #IMPLIED
    initCount CDATA #IMPLIED
    maxCount CDATA #IMPLIED
    testSql CDATA #IMPLIED>
<!ELEMENT Mappers ((Mapper|MapperSet)+)>
<!ATTLIST Mappers monitorInterval CDATA #IMPLIED>
<!ELEMENT Mapper (#PCDATA)>
<!ATTLIST Mapper file CDATA #REQUIRED>
<!ELEMENT MapperSet (#PCDATA)>
<!ATTLIST MapperSet
    basePath CDATA #REQUIRED
    filePattern CDATA #REQUIRED
	recursive (true|false) #IMPLIED>

<!ELEMENT Oracle (TNSName? Database? User? Password? Param* Pool Mappers)>
<!ATTLIST Oracle
    id ID #REQUIRED
    charset CDATA #REQUIRED
    tnsname CDATA #IMPLIED
    database CDATA #IMPLIED
    user CDATA #IMPLIED
    password CDATA #IMPLIED>
<!ELEMENT TNSName (#PCDATA)>

<!ELEMENT MySQL (Host? Port? Database? User? Password? Param* Pool Mappers)>
<!ATTLIST MySQL
    id ID #REQUIRED
    charset CDATA #REQUIRED
    host CDATA #IMPLIED
    port CDATA #IMPLIED
    database CDATA #IMPLIED
    user CDATA #IMPLIED
    password CDATA #IMPLIED>
<!ELEMENT Host (#PCDATA)>
<!ELEMENT Port (#PCDATA)>

<!ELEMENT SQLite (File? Param* Pool Mappers)>
<!ATTLIST SQLite
    id ID #REQUIRED
    file CDATA #IMPLIED
    serialize (true|false) #IMPLIED>
<!ELEMENT File (#PCDATA)>

<!ELEMENT PgSql (Host? Port? Database? User? Password? Param* Pool Mappers)>
<!ATTLIST PgSql
    id ID #REQUIRED
    charset CDATA #REQUIRED
    host CDATA #IMPLIED
    port CDATA #IMPLIED
    database CDATA #IMPLIED
    user CDATA #IMPLIED
    password CDATA #IMPLIED>

<!ELEMENT Custom (Param*)>
<!ATTLIST Custom
    id ID #REQUIRED
    sopath CDATA #REQUIRED
    charset CDATA #REQUIRED>
<!ELEMENT Param>
<!ATTLIST Param
	key CDATA #REQUIRED
	value CDATA #REQUIRED>

<!ELEMENT PoolConfigurations (PoolConfig+)>
<!ELEMENT PoolConfig (PingInterval? PingTest? TestOnBorrow? InitCount? MaxCount? TestSql?)>
<!ATTLIST Pool
    id ID #REQUIRED
    pingInterval CDATA #IMPLIED
    pingTest (true|false) #IMPLIED
    testOnBorrow (true|false) #IMPLIED
    initCount CDATA #IMPLIED
    maxCount CDATA #IMPLIED
    testSql CDATA #IMPLIED>

<!ELEMENT Logging (QueryId? Query? Result?)>
<!ELEMENT QueryId (#PCDATA)> <!ATTLIST QueryId show (true|false) #IMPLIED>
<!ELEMENT Query (#PCDATA)> <!ATTLIST Query show (true|false) #IMPLIED>
<!ELEMENT Result (#PCDATA)> <!ATTLIST Result show (true|false) #IMPLIED>

=== xcomart/libcmdbm/data/cmdbm_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cmdbm SYSTEM "cmdbm_config.dtd">
<Configuration>
    <Databases>
        <ODBC id="odbcName" charset="utf-8">
            <DSN></DSN>
            <User></User>
            <Password></Password>
            <Pool confRef="basePoolConfig" />
            <Mappers>
                <MapperSet basePath="" filePattern="" />
            </Mappers>
        </ODBC>
        <Oracle id="oracleName" charset="utf-8">
            <TNSName></TNSName>
            <User></User>
            <Password></Password>
            <Pool confRef="basePoolConfig" />
            <Mappers>
                <MapperSet basePath="" filePattern="" />
            </Mappers>
        </Oracle>
        <MySQL id="mysqlName" charset="utf-8">
            <Host>localhost</Host>
            <Port>3306</Port>
            <Database></Database>
            <User></User>
            <Password></Password>
            <Pool confRef="basePoolConfig" />
            <Mappers>
                <MapperSet basePath="" filePattern="" />
            </Mappers>
        </MySQL>
        <SQLite id="sqliteName">
            <File></File>
            <Pool confRef="basePoolConfig" />
            <Mappers>
                <MapperSet basePath="" filePattern="" />
            </Mappers>
        </SQLite>
        <PgSql id="pgsqlName" charset="utf-8">
            <Host>localhost</Host>
            <Port>5432</Port>
            <Database></Database>
            <User></User>
            <Password></Password>
            <Pool confRef="basePoolConfig" />
            <Mappers>
                <MapperSet basePath="" filePattern="" />
            </Mappers>
        </PgSql>
		<Custom id="custname">
			<Param key="key1">value1</Param>
			<Param key="key2">value2</Param>
			<Param key="key3">value3</Param>
		</Custom>
    </Databases>
    <Logging>
        <QueryId show="true" />
        <Query show="true" />
        <Result show="true" />
    </Logging>
    <PoolConfigurations>
		<PoolConfig id="basePoolConfig" pingInterval="30"
				pingTest="true" testOnBorrow="true">
            <InitCount>5</InitCount>
            <MaxCount>100</MaxCount>
            <TestSql>select 1 from dual</TestSql>
        </PoolConfig>
    </PoolConfigurations>
</Configuration>
